import type { LiveFeedbackReplayFixture } from "../src/lib/live-feedback-replay";

export const liveFeedbackFixtures: LiveFeedbackReplayFixture[] = [
  {
    id: "sales-pricing-objection",
    scenarioId: "sales-pitch",
    description: "Sales answer hits pricing pushback without handling the objection directly.",
    events: [
      { kind: "mode", timestamp: 0, agentSpeaking: true },
      {
        kind: "transcript",
        timestamp: 1500,
        bundle: {
          scenarioId: "sales-pitch",
          text: "The price feels expensive, but the platform does a lot and the team usually likes it once they see more features.",
          pace: 0.42,
          energy: 0.33,
          pitch: 0.38,
          turnCount: 4,
          confidence: 0.58,
          hedging: 0.22,
          fillerWords: 1,
          assertiveness: 0.52,
          sentiment: "neutral",
          newObjectivesHit: [],
        },
      },
      { kind: "mode", timestamp: 9000, agentSpeaking: false },
      {
        kind: "transcript",
        timestamp: 10000,
        bundle: {
          scenarioId: "sales-pitch",
          text: "The price feels expensive for your budget, and I still have not shown the ROI case clearly enough yet.",
          pace: 0.4,
          energy: 0.36,
          pitch: 0.35,
          turnCount: 5,
          confidence: 0.56,
          hedging: 0.18,
          fillerWords: 0,
          assertiveness: 0.57,
          sentiment: "neutral",
          newObjectivesHit: [],
        },
      },
      {
        kind: "transcript",
        timestamp: 12000,
        bundle: {
          scenarioId: "sales-pitch",
          text: "The price feels expensive for your budget, and I still have not shown the ROI case clearly enough yet.",
          pace: 0.41,
          energy: 0.35,
          pitch: 0.35,
          turnCount: 6,
          confidence: 0.55,
          hedging: 0.18,
          fillerWords: 0,
          assertiveness: 0.57,
          sentiment: "neutral",
          newObjectivesHit: [],
        },
      },
    ],
    expectedShown: [
      { type: "handle_objection", minTimestamp: 10000, maxTimestamp: 10000 },
    ],
    unexpected: ["pace_fast"],
  },
  {
    id: "vc-vague-story",
    scenarioId: "vc-pitch",
    description: "VC pitch stays broad and should trigger a specificity nudge.",
    events: [
      { kind: "mode", timestamp: 0, agentSpeaking: false },
      {
        kind: "transcript",
        timestamp: 5000,
        bundle: {
          scenarioId: "vc-pitch",
          text: "We help modern teams work better across the business, and the market is massive with demand from a lot of different customers.",
          pace: 0.47,
          energy: 0.44,
          pitch: 0.31,
          turnCount: 4,
          confidence: 0.61,
          hedging: 0.1,
          fillerWords: 0,
          assertiveness: 0.66,
          sentiment: "positive",
          newObjectivesHit: [],
        },
      },
    ],
    expectedShown: [
      { type: "be_specific", minTimestamp: 5000, maxTimestamp: 5000 },
    ],
    unexpected: ["hedging", "pace_fast"],
  },
  {
    id: "hard-conversation-empathy-gap",
    scenarioId: "conflict",
    description: "Hard conversation answer is tense and should trigger an empathy nudge.",
    events: [
      { kind: "mode", timestamp: 0, agentSpeaking: false },
      {
        kind: "transcript",
        timestamp: 7000,
        bundle: {
          scenarioId: "conflict",
          text: "I know this is frustrating, but every time we talk about this nothing changes and I am tired of repeating myself.",
          pace: 0.38,
          energy: 0.29,
          pitch: 0.46,
          turnCount: 3,
          confidence: 0.31,
          hedging: 0.08,
          fillerWords: 0,
          assertiveness: 0.42,
          sentiment: "negative",
          newObjectivesHit: [],
        },
      },
    ],
    expectedShown: [
      { type: "show_empathy", minTimestamp: 7000, maxTimestamp: 7000 },
    ],
    unexpected: ["pace_fast", "make_the_ask"],
  },
];
